signet=1
rpcuser=user
rpcpassword=password
txindex=1
blockfilterindex=1
peerblockfilters=1
coinstatsindex=1
dnsseed=0
persistmempool=1
uacomment=CustomSignet
rpcthreads=16
rpcservertimeout=600
rpcworkqueue=50
[signet]
daemon=0
listen=1
server=1
discover=1
signetchallenge=0014ce1329a95b72aa4c23c5210965e72a56e5966514
zmqpubrawblock=tcp://0.0.0.0:28334
zmqpubrawtx=tcp://0.0.0.0:28335
zmqpubhashtx=tcp://0.0.0.0:28333
zmqpubhashblock=tcp://0.0.0.0:28332
zmqpubsequence=tcp://0.0.0.0:28336
rpcbind=0.0.0.0:38332
rpcallowip=0.0.0.0/0
whitelist=0.0.0.0/0
fallbackfee=0.0002
acceptnonstdtxn=1
v2transport=1
minrelaytxfee=0.0
blockmintxfee=0.0
dustRelayFee=0.0
maxtxfee=10
debug=1
