services:
  bitcoind-miner:
    container_name: bitcoin-miner
    # image: alpen_signet:1.0
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      RPCUSER: user
      RPCPASSWORD: password
      MNEMONIC: "xxxxx"
      MINERENABLED: "1"
      MAXTXFEE: "10"
      SIGNETCHALLENGE: 0014ce1329a95b72aa4c23c5210965e72a56e5966514
      
    volumes: 
      - ./bitcoin.conf:/root/.bitcoin/bitcoin.conf
    ports:
      - "28332:28332"
      - "28333:28333"
      - "28334:28334"
      - "38332:38332"
      - "38333:38333"
      - "38334:38334"
